### ISSUE TITLE
Rackspace CDN Cloudfiles

### ISSUE THREAD

**Issue by vhuerta** [chrisben/imgcache.js#143]
Im trying to use this library with Rackspace Cloudfiles using the CDN but im getting this error 

XMLHttpRequest cannot load http://f66aeee92e6b184cba3a-89a047f0e01b2380e61e9d1cc03b16b1.r37.cf1.rackcdn.com/wM8TPZnX4JcF5RfrK.jpeg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Do you know any about this?

**Comment by chrisben** [comment]
This is because your CDN doesn't allow CORS for your localhost. This is something you seem to be able to fix within your rackcdn account: http://stackoverflow.com/questions/30067314/using-rack-cors-with-rackspace-cdn-issues#30103143

This problem has nothing to do with this library so I'm closing the issue here.

**Comment by vhuerta** [comment]
Yes i found that solution a couple days ago sorry for not close this issue before. 

regards
