### ISSUE TITLE
ImgCache.overridables.log() not working in cordova

### ISSUE THREAD

**Issue by miqmago** [chrisben/imgcache.js#186]
I was going crazy because I forgot to call `ImgCache.init()` before `ImgCache.isCached(...)`

`isCached` is calling `getCachedFile` , which is calling `Private.isImgCacheLoaded` and it returns `false`. So `getCachedFile` returns and no callback is called. The cordova app get's hanged waiting for the `callback` to be called which in turn it never gets called:

```js
        if (!Private.isImgCacheLoaded() || !response_callback) {
            return; // ---> response_callback never get's called
        }
```

```js
    ImgCache.isCached = function (img_src, response_callback) {
        ImgCache.getCachedFile(img_src, function (src, file_entry) {
            response_callback(src, file_entry !== null);
        });
    };
```

Maybe a solution should be to provide an error function for isCached, etc..?

**Comment by chrisben** [comment]
I see what happened there. Thanks for getting down to the bottom of it.

I strongly recommend everyone to use the promise version of imgcache because it handles the call to `init` automatically.
The current version in master is using Q which looks dated but the [future version](https://github.com/chrisben/imgcache.js/blob/2.x/lib/imgcache-promise.js) should be simpler.

For now I will not add more code around `isCached`, this issue itself is documentation.
