### ISSUE TITLE
ImgCache does not load cached image

### ISSUE THREAD

**Issue by JcDenton86** [chrisben/imgcache.js#98]
Hi, I am caching images fetched with $http like this: 
```
var atsize = respdata.data.posts[i].attachments.length;
    var images=[];
    for(j=0;j<atsize;j++){
        images.push(respdata.data.posts[i].attachments[j].url);
        ImgCache.cacheFile(respdata.data.posts[i].attachments[j].url);
    }
```
Of course I have initialized the ImgCache. So, the 1st time the app runs i am downloading and caching the images ( i checked using file explorer that the images are downloaded). I have also created a small angularjs directive like the one bellow: 
```
(function(angular) {
    "use strict";
    var ngImgCache = angular.module('ngImgCache', []);

    ngImgCache.directive('ngCache', function() {
        return {
            restrict: 'A',
            link: function(scope, el, attrs) {	
                attrs.$observe('ngSrc', function(src) {
			ImgCache.useCachedFile(el);
                });
		attrs.$observe('divBg', function(src) {
			ImgCache.getCachedFileURL(src, function(src, dest) {
			el.css({'background-image': 'url(' + dest + ')' });
                       });
                 });
            }
        };
    });
})(angular);
```
So in my html i can use `<img ng-cache ng-src={{srcURL}} />`

Running the application while online i am seeing the logs and the images are downloaded and cached and the cached version is used. Running the application offline i get the error:

01-30 15:10:44.476: E/AndroidProtocolHandler(29088): Unable to open asset URL: file:///android_asset/www/[%22http:////example.com//entries//images//uploads//2014//11//DSC_31.jpg%22

While the ImgCache should use the cached version of the ng-src value as applied from the directive, it is not. What' s wrong with the implementation? Is that an issue of ImgCache or am I doing something wrong?

My setup is: Cordova 3.6.4, Angular 1.3 and Onsen UI 1.2.1

Thank you in advance

**Comment by JcDenton86** [comment]
Hi, any news on that? an answer or advice would be really helpful

**Comment by BrunoCartier** [comment]
Hey,

Instead of using your own directive, could you please try to use one of the existing libraries that seems to fit your needs? Here are two of them:
- [ngImgCache](https://github.com/sunsus/ngImgCache/)
- [angular-imgcache.js](https://github.com/jBenes/angular-imgcache.js)

This way, you are going to be sure if the problem comes from your implementation or not.

**Comment by JcDenton86** [comment]
Thanks for your response,
I have tried these two libraries without success yet, that's why I created a custom directive which works for the part of downloading and caching. I have used this library again in the past but with jquery mobile and earlier versions of cordova (v 3.0) and I had no issues at all. So it might be angular related or the newest versions of cordova and the URI scheme.. Did you have successfully applied it with one of these libraries? 
If yes can you share how?

**Comment by BrunoCartier** [comment]
When I was using imgcache in a project (some months ago), no specific Angular library was existing.
So I created my own simple one, wrapped in a service: [angular-imgcache](https://github.com/ActivKonnect/angular-imgcache). It doesn't provide a directive though, & needs Ionic since I used `ionic.Platform.ready` (that can be easily changed). That's why I did not specify it here: it does not fit your needs.

For your information, all was working with those versions:
- Cordova 3.6
- Angular 1.2.17
- Ionic 1.0.0-beta.10
- [Custom imgcache.js](https://github.com/BrunoCartier/imgcache.js/) (just making EntryGetURL function public)

The fact that none of the quoted libs work for you is very strange :/
Good luck with your issue!

**Comment by chrisben** [comment]
I won't be able to help you much on the angular side, though I can see in your error that the URL is clearly wrong. Can you double check that whatever urls you feed to imgcache are indeed correct and don't contain any wrong characters (like ```/[%22```).
Have you used any option on ImgCache, or are you using the default options?

I would recommend you strip as much code as you can and create a simpler test case to understand where things go wrong.

**Comment by JcDenton86** [comment]
OK it was strange to me too the URL pattern. I am fetching a json object where there is an array with images and I store everything I need in a database(sqlite). And the images are showing correctly while online. When I run the app offline I fetch the data from the database and the images URL are returnd in this format.. I will check that

**Comment by chrisben** [comment]
That's something to investigate indeed, it looks like [ ... ] is a json array that is considered as a string. Are you sure you call JSON.parse()  on that json data to make it into a javascript array?

**Comment by JcDenton86** [comment]
fixing the URL pattern worked by using my directive. Thanks!
